version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
    file_exists_behavior: RETAIN
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh 
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh 
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      runas: ec2-user
