version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - ls -al
      - sudo npm install

  build:
    commands:
      - sudo npm run build

artifacts:
  files:
    - '**/*'
  name: AutoCrashData
