version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - npm run export

artifacts:
  files:
    - 'out/**/*'
  name: AutoCrashData

cache:
  paths:
    - 'node_modules/**/*'
    - '.next/cache/**/*'
